steps:
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            # O plugin @semantic-release/github já vem instalado por padrão, 
            # não precisa listar aqui, mas precisa estar no release.config.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # ESSENCIAL para criar a Release no GitHub